src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Away_Team_Name__c</fullName>
        <formula>Away_Team__r.Team_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Away Team Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Team_Name__c</fullName>
        <formula>Home_Team__r.Team_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Home Team Name</label>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HomeController.cls
public with sharing class HomeController {
	private Game__c nextGame, previousGame;
	public HomeController() {
		String currentEdition = '2014';
		if(GameUtil.isUserPlaying()){
			nextGame = GameUtil.getNextGameAsPlayer(UserInfo.getUserId(), currentEdition);
			previousGame = GameUtil.getPreviousGameAsPlayer(UserInfo.getUserId(), currentEdition);
		} else {
			nextGame = GameUtil.getNextGameAsRef(UserInfo.getUserId(), currentEdition);
			previousGame = GameUtil.getPreviousGameAsRef(UserInfo.getUserId(), currentEdition);
		}

		if(GameUtil.isUserPlaying()){
			myGroupId = GameUtil.getGroupId(UserInfo.getUserId(), currentEdition);
		} else {
			myGroupId = GameUtil.getFirstGroupId(currentEdition);
		}
	}

	public String myGroupId {
		get; private set;
	}
	
	public String nextGameHomeTeam {
		get {
			return nextGame==null?null:nextGame.home_team_name__c;
		}
	}
	
	public String nextGameAwayTeam {
		get {
			return nextGame==null?null:nextGame.away_team_name__c;
		}
	}

	public String previousGameHomeTeam {
		get {
			return previousGame==null?null:previousGame.home_team_name__c;
		}
	}
	
	public String previousGameAwayTeam {
		get {
			return previousGame==null?null:previousGame.away_team_name__c;
		}
	}
}