src/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Away_Team_Name__c</fullName>
        <formula>Away_Team__r.Team_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Away Team Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Away_Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Away Team</label>
        <referenceTo>Group_Membership__c</referenceTo>
        <relationshipLabel>Games (Away Game)</relationshipLabel>
        <relationshipName>Away_Games</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Tournament_Group__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Home_Team_Name__c</fullName>
        <formula>Home_Team__r.Team_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Home Team Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Home Team</label>
        <referenceTo>Group_Membership__c</referenceTo>
        <relationshipLabel>Home Games</relationshipLabel>
        <relationshipName>Home_Games</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Games</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>When__c</fullName>
        <label>When</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>completed</label>
        <type>Checkbox</type>
    </fields>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Group_Membership__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Tournament_Group__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Group_Memberships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Team Participation</label>
        <referenceTo>Team_Participation__c</referenceTo>
        <relationshipLabel>Group Memberships</relationshipLabel>
        <relationshipName>Group_Memberships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Group Membership</label>
    <nameField>
        <displayFormat>GM-{0000}</displayFormat>
        <label>Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team_Membership__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Player</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team_Participation__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Membership</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Edition__c</fullName>
        <label>Edition</label>
        <referenceTo>Tournament_Edition__c</referenceTo>
        <relationshipLabel>Team Participations</relationshipLabel>
        <relationshipName>Team_Participations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Participations</relationshipLabel>
        <relationshipName>Team_Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Participation</label>
    <nameField>
        <displayFormat>TP-{0000}</displayFormat>
        <label>Team Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tournament_Edition__c.object
<CustomObject>
    <label>Tournament Edition</label>
    <nameField>
        <label>Tournament Edition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Editions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tournament_Group__c.object
<CustomObject>
    <fields>
        <fullName>Tournament_Edition__c</fullName>
        <label>Tournament Edition</label>
        <referenceTo>Tournament_Edition__c</referenceTo>
        <relationshipLabel>Tournament Groups</relationshipLabel>
        <relationshipName>Tournament_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tournament Group</label>
    <nameField>
        <label>Group</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournament Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GameUtil.cls
public with sharing class GameUtil {
	private static String PLAYER_PROFILE = 'Player';

	/*
	*  Returns true if user is assigned to the player profile, meaning he'll be playing the tournament. 
	*  In case this is false, we can assume the user is a referee
	*/
	public static boolean isUserPlaying() {
		Profile profile = [select name from Profile where Id = :UserInfo.getProfileId()][0];
		return profile.name.equalsIgnoreCase(PLAYER_PROFILE);
	}
	/*
	*   Returns the next game scheduled for the user as a player or null in case no games scheduled in the future
	*/
	public static Game__c getNextGameAsPlayer(String userId, String currentEdition) {
		return getRelevantGameAsPlayer(userId, currentEdition, true);
	}
	
	/*
	*   Returns the previous game played by the user or null in case this player hasn't played any games 
	*/
	public static Game__c getPreviousGameAsPlayer(String userId, String currentEdition) {
		return getRelevantGameAsPlayer(userId, currentEdition, false);
	}
	
	private static Game__c getRelevantGameAsPlayer(String userId, String currentEdition, boolean nextGame) {
		Game__c game;
		try {
			Id groupMembershipId = [select id from group_membership__c where team__c in 
								(select team__c from team_membership__c where player__c = :userId and team__r.edition__r.name=:currentEdition) limit 1][0].id;
			try {
				if (nextGame) {
					game = queryNextGameAsPlayer(groupMembershipId);
				} else {
					game = queryPreviousGameAsPlayer(groupMembershipId);
				}
			} catch (ListException e) {
			// swallow in case no previous game
			}
		} catch (ListException e) {
			// in case we're not in any teams this edition
		}
		
		return game;
	}
	
	private static Game__c queryNextGameAsPlayer(Id groupMembershipId) {
		return [select name, home_team_name__c, away_team_name__c from game__c 
					where completed__c = false and when__c > :DateTime.now() and (away_team__c = :groupMembershipId or home_team__c = :groupMembershipId) order by when__c asc limit 1][0];
	}
	
	private static Game__c queryPreviousGameAsPlayer(Id groupMembershipId) {
		return [select name, home_team_name__c, away_team_name__c from game__c 
					where completed__c = true and (away_team__c = :groupMembershipId or home_team__c = :groupMembershipId) order by when__c desc limit 1][0];
	}
	
	/*
	*   Returns the next game scheduled for the referee user or null in case no games scheduled in the future
	*/
	public static Game__c getNextGameAsRef(String userId, String currentEdition) {
		return getRelevantGameAsRef(userId, currentEdition, true);
	}
	
	/*
	*   Returns the previous game scheduled for the referee user or null in case no games were refereeed by this user
	*/
	public static Game__c getPreviousGameAsRef(String userId, String currentEdition) {
		return getRelevantGameAsRef(userId, currentEdition, false);
	}
	
	private static Game__c getRelevantGameAsRef(String userId, String currentEdition, boolean nextGame) {
		Game__c game;
		try {
			try {
				if (nextGame) {
					game = queryNextGameAsRef(userId, currentEdition);
				} else {
					game = queryPreviousGameAsRef(userId, currentEdition);
				}
			} catch (ListException e) {
			// swallow in case no previous game
			}
		} catch (ListException e) {
			// in case we're not in any teams this edition
		}
		
		return game;
	}
	
	private static Game__c queryNextGameAsRef(String userId, String edition) {
		return [select name, home_team_name__c, away_team_name__c from game__c 
					where completed__c = false and when__c > :DateTime.now() and referee__c = :userId and group__r.tournament_edition__r.name=:edition order by when__c asc limit 1][0];
	}
	
	private static Game__c queryPreviousGameAsRef(String userId, String edition) {
		return [select name, home_team_name__c, away_team_name__c from game__c 
					where completed__c = true and referee__c =:userId and group__r.tournament_edition__r.name=:edition order by when__c desc limit 1][0];
	}
	
    public static String getGroupId(String userId, String currentEdition) {	
			Id groupMembershipId = [select id from group_membership__c where team__c in 
								(select team__c from team_membership__c where player__c = :userId and team__r.edition__r.name=:currentEdition) limit 1][0].id;
			return groupMembershipId;
    }

    public static String getFirstGroupId(String currentEdition) {	
			Id groupMembershipId = [select id from group_membership__c 
			where group__r.tournament_edition__r.name =:currentEdition order by group__r.name limit 1][0].id;
			return groupMembershipId;
    }
}